### ISSUE TITLE
wlsh_nodes："Image Save with Prompt File (WLSH)": WLSH_Image_Save_With_Prompt_File, not save .txt文件

### ISSUE THREAD

**Issue by vxkj1211** [wallish77/wlsh_nodes#5] opened 2023-08-13 14:51 UTC
WAS NS Error: The path `./output` specified doesn't exist! Defaulting to `D:\ComfyUI_windows_portable/ComfyUI\output` directory.
WAS NS Error: The path `./output` doesn't exist!
WAS Node Suite Error: Unable to save file `./output\sdvn7Realartxl_beta-329605572871743.txt`

**Comment by wallish77** [comment] 2023-08-13 19:11
There's a couple of things going on here:

First is that it is saying that the path `./output` doesn't exist.  This is strange as it follows up by saying that the folder exists.  This must mean that the issue is possibly with the relative path `./` not working because the actual current working directory is now the `ComfyUI` folder.  

I'm not on windows so I can't test it, but if you change the `./output` to just `output`, does it work?

**Comment by wallish77** [comment] 2023-08-14 01:43
Should be fixed with commit 7354fdb33188ce4cabb2be6e97e5c7069dbbe816

**Closed by wallish77** 2023-08-14 01:43 UTC
